FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /app

# copy csproj and restore as distinct layers
COPY . .
RUN dotnet restore

WORKDIR /app/CheckoutTechTest.WebApi.E2E

ENTRYPOINT ["dotnet", "test"]